### ISSUE TITLE
extra 10 bytes to start get_image() ?

### ISSUE THREAD

**Issue by mdougher** [devsnd/tinytag#100]
Hi, 
not sure if this is an issue, or I am not using TinyTag properly!

I am using tinytag to get image data embedded in my audio files, and passing the image data into PIL/Pillow. i have noticed that *some* of the image data cannot be loaded.
upon closer inspection of the data, it appears that I am getting a strange 10 B prefix for all of the ones that fail.

Here's a code fragment:
```
from tinytag import TinyTag
from PIL import Image
import io

filename = 'some/path/to/a/file.mp3
tags = TinyTag.get(filename, image=True)
image_data = tags.get_image()
img = Image.open(io.BytesIO(image_data))
# ^^^ this will fail for *some* of my audio files
```
I noticed that it is consistent which files fail and which pass, so it must be something with my audio files.
when i print out the start of the data for one of these, and compare it to a file that is OK, i see a difference:

Good File: b'\xff\xd8\xff\xe0\x00\x10JFIF....'
Bad File: b'o\x00v\x00e\x00r\x00\x00\x00\xff\xd8\xff\xe0\x00\x10JFIF......'
so, it looks like the Bad File has a prefix of 10 bytes, followed by the same start as 'good file'.
b'o\x00v\x00e\x00r\x00\x00\xoo'
(does that say 'o v e r   ' ?? weird...)

is this expected? i'm not sure why this is showing up, and only for some audio files.
my script seems to work just fine if i do this:
```
if image_data[:10] == b'o\x00v\x00e\x00r\x00\x00\x00':
    image_data = image_data[10:]
```
but this feels a bit clumsy!

anyway, thanks in advance for taking a look! I can provide my audio files for you if needed.

**Comment by mdougher** [comment]
ok, so after giving this a lot more thought, i think this is an issue with my audio files. seems to follow ALL of the files that have been downloaded from bandcamp.com have this... 
if i use musicbrainz picard to extract the image, it does not have this leading 10 B. i can then re-apply this image to the mp3 using picard and then view it from tinytag and the leading 10 B are no longer there.

so, it sounds to me like bandcamp is sticking this in there?
it seems most places can ignore it, probably by searching for the 0xff 0xd8 0xff 0xe0 0x00 0x10 JFIF header. the head unit in my car does no such thing, and displays no artwork. 

looks like i have some metadata work to do....

**Comment by devsnd** [comment]
Hey @mdougher 

Sorry for the late answer! One of the benefits of fatherhood is having no free time at all anymore :sweat_smile: 

Could you provide a sample file with the broken artwork? I think searching for the JFIF header might be an okayish hack, but I'd rather figure out whats really going on as artwork is not guaranteed to be a jpeg as well.

**Comment by mdougher** [comment]
> Hey @mdougher
> 
> Sorry for the late answer! One of the benefits of fatherhood is having no free time at all anymore sweat_smile
> 
> Could you provide a sample file with the broken artwork? I think searching for the JFIF header might be an okayish hack, but I'd rather figure out whats really going on as artwork is not guaranteed to be a jpeg as well.

no worries there, i totally understand!
again, i don't believe this to be a tinytag issue after spending more time on this. My gut tells me this is coming from bandcamp's download process... But i'll send you what i can and you can make your own decision.

For unrelated reasons, i went through my whole music library to get musicbrainz metadata, and part of that involves updating the album art for each mp3 file.

So, in order to get you a sample file, I am doing a fresh download of an album from bandcamp. I chose https://flamingosis1.bandcamp.com/album/maniacs as it is a fairly recent release. (omg its a year old?! thanks, 2020... (also pretty cheap if you wanted to purchase for yourself and see?))
anyway, it downloads as a zip of the whole album. I don't believe i can download just a single track since i purchased the whole album? (side note: after this i'll try again with a single that i purchased from bandcamp and report back)

I am running ubuntu 20.04. i right click the zip file in my downloads and select 'Extract Here' (probably a similar process as any unzip operation, but figure its worth mentioning)
From there, i have a folder of the album contents. i do the process i mentioned earlier 
```
from tinytag import TinyTag
from PIL import Image
import io

filename = 'some/path/to/a/file.mp3
tags = TinyTag.get(filename, image=True)
image_data = tags.get_image()

>>> image_data[:20]
b'o\x00v\x00e\x00r\x00\x00\x00\xff\xd8\xff\xe0\x00\x10JFIF'
```
Using the track i am attaching to this comment. Only modifications i made after the download - rename to fit my schema, and i zipped it up to attach to this comment.

[02 Future Love.zip](https://github.com/devsnd/tinytag/files/6218273/02.Future.Love.zip)

**Comment by mdougher** [comment]
i see the same thing when i download a single track from bandcamp. Seems you can only do this when you purchase a single or an individual track. anyway, it looks the same, but i'll attach it here. Only changes to this one is zipping it up to attach to this comment. otherwise, it is exactly as i downloaded it.

My usual download flavor from bandcamp is MP3 V0. I changed to MP3 320, same thing.

i tried downloading it as a FLAC file, but that doesn't seem to include the album art image (?)
downloading as 'AAC' gives me an m4a file that _does not_ have the issue (!)
There are a handful of other format choices for download, let me know if you want me to try others...

attaching both the mp3 (320, i think?) and the aac/m4a files. flac version too large to attach here : ( again, only changes i made were zipping them up.

[Rollergirl! - #billyocean.mp3.zip](https://github.com/devsnd/tinytag/files/6218299/Rollergirl.-.billyocean.mp3.zip)
[Rollergirl! - #billyocean.m4a.zip](https://github.com/devsnd/tinytag/files/6218300/Rollergirl.-.billyocean.m4a.zip)

**Comment by mdougher** [comment]
> I think searching for the JFIF header might be an okayish hack, but I'd rather figure out whats really going on as artwork is not guaranteed to be a jpeg as well.

just want to say again, that i don't believe this to be an error in tinytag, but maybe you could make an argument for attempting to support stuff like this? i agree that your idea of searching for the header sounds a little hack-ish... from my point of view, i'm not sure i would want that to be always on, but maybe having an option to turn on different kinds of image parsing might be less hack-y? 

and just to reiterate, this is no longer a problem for me - my archival process already involves updating metadata from musicbrainz - this applies a new image to the mp3 file and does not have this issue. So please, don't feel like you need to implement any hack-ish stuff in there just to accomodate me : )

**Comment by aw-was-here** [comment]
So after adding the AIFF support in #111 & #112, I'm seeing this issue with Bandcamp built AIFF's. I have a hypothesis as to what is going wrong.  What I think TinyTag is missing is part of the spec implementation:

```
     <Header for 'Attached picture', ID: "APIC">
     Text encoding      $xx
     MIME type          <text string> $00
     Picture type       $xx
     Description        <text string according to encoding> $00 (00)
     Picture data       <binary data>
```

o\x00v\x00e\x00r\x00\x00 == over\00. Sure looks like 'cover'. Let's pop it into a hex editor:

```
164630620  \0   m  \0   p  \0   .  \0   c  \0   o  \0   m  \0  \0  \0   A
164630640   P   I   C  \0 002 024   h  \0  \0 001   i   m   a   g   e   /
164630660   j   p   e   g  \0 003 377 376   c  \0   o  \0   v  \0   e  \0
164630700   r  \0  \0  \0 377 330 377 340  \0 020   J   F   I   F  \0 001
```
APIC ... image/jpeg ... cover ... JFIF.

It really looks to me like TinyTag isn't handling the header correctly. The description is likely getting misinterpreted and the tail end [over\00] becomes part of the image.
