### ISSUE TITLE
No video bitrate from .mp4 files

### ISSUE THREAD

**Issue by JDonner** [devsnd/tinytag#101]
You do get a bitrate, but it's audio. I don't see anything for the video bitrate. 

Installing collected packages: tinytag
Successfully installed tinytag-1.5.0

>>> from tinytag import TinyTag
>>> tags = TinyTag.get('my-video.mp4')
>>> tags
{"album": null, "albumartist": null, "artist": null, "audio_offset": null, "bitrate": 125.588, "channels": 2, "comment": null, "composer": null, "disc": null, "disc_total": null, "duration": 47.95, "filesize": 6006976, "genre": null, "samplerate": 44100, "title": null, "track": null, "track_total": null, "year": null}

Whereas ffmpeg finds: 

$ ffmpeg -i my-video.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'my-video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:00:47.95, start: 0.000000, bitrate: 1002 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 871 kb/s, 24 fps, 23.98 tbr, 90k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

**Comment by devsnd** [comment]
Hello Jeff, I'm sorry to inform you that tinytag only reads metadata from audio files, video files are not supported.

Good luck with your video project however, have a nice day day!
