### ISSUE TITLE
Feature Request: Include Additional Tags

### ISSUE THREAD

**Issue by RileyTheEcon** [devsnd/tinytag#104]
Would it be possible to include coverage of additional tags, like "Director"?

I am trying to build a program for organizing my library of movies (MP4s) and TinyTag could help a lot with extracting information saved in each of the files; however, it currently does not support the 'director' tag. I tried to edit the tinytag.py code to add this functionality by including an entry for "directors" every time "composer" is used. For the `META_TREE_DATA`, I used '\xa9dir'. This unfortunately did not work.
From what I can tell from experimenting with the `_traverse_atoms` function, the code might be skipping over the relevant tag or the information is saved under a different tag.

**Comment by devsnd** [comment]
Hey @RileyTheEcon 

TinyTag isn't really meant for movie files, but I'd happily support additional meta data.

I thought it would be nice to have a section in the tinytag return value for any additional data that has been found in the tag:

e.g.
```
TinyTag.get(...)
> {
  "title": "something",
  "year": 2021,
  "extra": {
     "director": "John Woo",
     "other meta data": "which isn't common to multiple formats",
  }
}
```

in that way tinytag always reliably returns audio meta data in the same format, and additional meta data can also be retrieved, but is not guaranteed to exist.

Could you provide a sample file for me?
