### ISSUE TITLE
First character of title, artist and album cut off

### ISSUE THREAD

**Issue by Crozzers** [devsnd/tinytag#106]
I noticed that, when using tinytag on certain mp3 files, the first letter of the title, artist and album are cut off.
```python
from tinytag import TinyTag
tags = TinyTag.get('ERB_Tony_Hawk_VS_Wayne_Gretsky.mp3')
print(tags.title)
> 'ony Hawk VS Wayne Gretzky' # should be 'Tony Hawk VS Wayne Gretsky'
print(tags.artist)
> 'pic Rap Battles Of History' # should be 'Epic Rap Battles Of History'
print(tags.album)
> 'RB' # should be 'ERB'
```
When using `mutagen.easyid3` the problem dissapears
```python
from mutagen.easyid3 import EasyID3
tags = EasyID3('ERB_Tony_Hawk_VS_Wayne_Gretsky.mp3')
print(tags['title'][0])
> 'Tony Hawk VS Wayne Gretsky'
print(tags['artist'][0])
> 'Epic Rap Battles Of History'
print(tags['album'][0])
> 'ERB'
```

I have traced the problem to `ID3._decode_string` in `tinytag.py`.
They bytestring input (for the title) is:
`b'\x01T\x00o\x00n\x00y\x00 \x00H\x00a\x00w\x00k\x00 \x00V\x00S\x00 \x00W\x00a\x00y\x00n\x00e\x00 \x00G\x00r\x00e\x00t\x00z\x00k\x00y\x00'`

On line 720 (`bytestr = bytestr[1:]`) it cuts it to:
`b'T\x00o\x00n\x00y\x00 \x00H\x00a\x00w\x00k\x00 \x00V\x00S\x00 \x00W\x00a\x00y\x00n\x00e\x00 \x00G\x00r\x00e\x00t\x00z\x00k\x00y\x00'`

Then on line 730 it says `bytestr = bytestr[2:] if len(bytestr) % 2 == 0 else bytestr[2:-1]` which then removes the `T\x00` from the start of the string. This ends up with the first character cut off.

I am not familiar with the ID3 spec so it is possible that this file is invalid but since EasyID3 managed to parse it I am unsure.

Many Thanks

**Comment by devsnd** [comment]
Hey @Crozzers 

Can you please provide a sample file?

It's possible that there a file formats that are not really compliant with the standards, but I want tinytag to be as compatible as possible, so I'd rather fix these quirks instead of sticking to the - admittedly crappy - standards.

**Comment by Crozzers** [comment]
I think its entirely possible that the file is invalid because I ripped it from YouTube with YouTube-DL so I wouldn't be surprised if that generated some inconsistencies.

Here's a drive link to the file
https://drive.google.com/file/d/1Tvf8eyjxORmuDLc3mEuXuw0YDtudR5xC/view?usp=sharing

**Comment by devsnd** [comment]
Hey @Crozzers,

I was able to reproduce the issue and have created a fix. You can use the version in the master branch to get the fix right away. It will also be part of the next release of tinytag.

Thanks a lot for reporting the bug and for providing a sample.

I wish you a nice day, here's a piece of cake for you :cake:
