### ISSUE TITLE
Unable to import module 'tinytag'

### ISSUE THREAD

**Issue by PythonMods** [devsnd/tinytag#107]
I have used this code:
`from tinytag import TinyTag, TinyTagException`
And I get an error saying: "No module named 'tinytag'"
I have definitely installed it using: 'pip install tinytag' 
I am using Python 3.9.1 x64.

**Comment by devsnd** [comment]
Hey @PythonMods 

I have just created a virtual env using python 3.9.**2** on my machine (maybe the patch-level does the trick, but I doubt it), installed tinytag in there and `from tinytag import TinyTag, TinyTagException` worked without a hitch. There must be something off with your python installation or your `PYTHONPATH` maybe?

I will close the bug for now, please feel free to reopen if you have a way for me to reproduce it.
