### ISSUE TITLE
Deprecation Warning in python 3.9

### ISSUE THREAD

**Issue by idotobi** [devsnd/tinytag#109]
**Describe the bug**
There's a deprecation warning when using tinytag in python 3.9 which would cause a problem in python 3.10.

**To Reproduce**
 1. Import `tinytag` in your python project
 2. Run pytest

**Expected behavior**
No Deprecation Warning

**Sample File**

```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import MutableMapping, OrderedDict

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by devsnd** [comment]
Your PR fixes the warning, right? I'm closing this issue then. Feel free to reopen if there's still a problem

**Comment by punchagan** [comment]
Thanks for this fix, @devsnd. Would it be possible to put out an update on PyPI with this fix? Thanks for the wonderful package, `tinytag`!
