### ISSUE TITLE
Load metadata from URL

### ISSUE THREAD

**Issue by amiantos** [devsnd/tinytag#114]
**Is your feature request related to a problem? Please describe.**
It'd be nice if I could load metadata from a file URL versus downloading the file first to grab the metadata.

**Describe the solution you'd like**
Provide a URL instead of a path to a file when doing `get`.

**Describe alternatives you've considered**
I can download the file locally and use `NamedTemporaryFile` to load it, but maybe there's a way to load metadata from a file without loading the entire file contents.

**Comment by devsnd** [comment]
Hey Brad,

Thanks for your suggestion!

I'm sorry but this features outside of the scope of this project. Most of
the logic relies on being able to seek freely inside of the file. Therefore
there is no upside in streaming any data from an URL (as the file would
need to be downloaded fully in any case).

Using a named temporary file and the requests module you can achieve what
you want with just two lines of code.

I think in term of where the project is heading I would rather have more
low level access than a higher abstraction level in there: so for example
having the ability to pass in a stream of bytes.

Anyway, thanks again for your interest and I wish you a great weekend!

**Comment by amiantos** [comment]
No problem. I agree with passing in a stream of bytes, that would have also solved my 'problem' as well. Thank you for the very useful library.
