### ISSUE TITLE
[BUG] Version 1.6 returns invalid content of cover image from mp3-file

### ISSUE THREAD

**Issue by Cykooz** [devsnd/tinytag#117]
Example of mp3 file with cover image:
[12oz.zip](https://github.com/devsnd/tinytag/files/7084033/12oz.zip)

`tinytag 1.5` returns a valid image.
`tinytag 1.6` returns an image without a few bytes (15 bytes) from the start of the image data.

**Comment by devsnd** [comment]
Hey @Cykooz ,

Thanks for the report and for providing a sample file. I was able to reproduce and to fix the issue. It will be part of the next release. Until then, you can use the version from the master branch to get the fix right away
