### ISSUE TITLE
[BUG] multiple text tags in MP4 does only return the first

### ISSUE THREAD

**Issue by armsby** [devsnd/tinytag#118]
**Describe the bug**
if your MP4 file contains multiple text tag b'----' it only returned the first,

**To Reproduce**
any file with multiple ---- tags

**Expected behavior**
as those tags has there own name in the I would expected it to use that and put it in the extra dict

"                     pos: 8857073 atom: b'----' len: 78"
"                         pos: 8857081 atom: b'mean' len: 28"
"                         pos: 8857109 atom: b'name' len: 16"
"                         pos: 8857125 atom: b'data' len: 26"
'fieldname: extra.text'
'value: B082MSHYLN'

is this case it is the ASIN number of an audiobook

**Sample File**
file can be provided on request as it is no small files

**Comment by devsnd** [comment]
Hey @armsby ,

Yes, please provide a sample file so that I can take a look

**Comment by mathiascode** [comment]
Closing in favor of https://github.com/devsnd/tinytag/issues/166
