### ISSUE TITLE
this one file...

### ISSUE THREAD

**Issue by tjconnelly** [devsnd/tinytag#120]
hello, tinytag is wonderful and i'm sorry to post what is basically a support forum kind of question, but:

there's this one file i have where tinytag doesn't return artist info. given error rates overall i'm inclined to believe tinytag, but the thing is i've rewritten the artist info with both Meta and Swinsian and still no dice. 

do you, or anyone in the community, have any advice for ironing this out? on a current-OS Mac with many years of unix/code under my belt, happy to try semi-crazy plans.

sorry to post what is not, i assume, actually an tinytag issue, it's just driving me nuts and i'm hoping y'all might have ideas. 

thanks again

**Comment by tjconnelly** [comment]
i see now also some folks are attaching files; i'm happy to do that if asked

**Comment by devsnd** [comment]
Hey @tjconnelly ,

Yes, please provide the file in question, so we can reproduce the error, so that we can fix it in turn :)

**Comment by tjconnelly** [comment]
i am the monster who never noted which file it was and now cleaning up tickets i realize i did not follow up. if i encounter it again i will revisit, meanwhile apologies, thanks.
