### ISSUE TITLE
Feature Request: Adding Song Titles

### ISSUE THREAD

**Issue by trialtest-dev** [devsnd/tinytag#122]
**Is your feature request related to a problem? Please describe.**
I'm a very new python dev trying to make a simple script to extract file names and sound titles from wav files. Audacity automatically puts labels into the title metadata when I export, which is awesome since I transcribe with them. Unfortunately, using file.title() returns the name of the file, not the "Title" of the song circled in red.
![image](https://user-images.githubusercontent.com/86586065/142715712-15a89bdf-b4f9-49d8-b128-75b0fcf87887.png)

**Describe the solution you'd like**
I'd love to see a tag added where I can access the "Title" of the song according to Windows, not the file name.

**Describe alternatives you've considered**
Some google searching showed that there weren't any other python libraries that could access as many tags as this. :(

**Additional context**
If I missed something, please let me know! I'd love some pointers to help me out.

**Comment by devsnd** [comment]
Hey @trialtest-dev ,

I'm not sure I understand. Could you be so kind to provide a sample file and the code you run and the expected output?

Because you are able to get the meta-data title from a track by using this code:
```
from tinytag import TinyTag
tag = TinyTag.get('your_file.mp3')
print(tag.title)
```

I'm not sure what you differently to get the filename?

**Comment by trialtest-dev** [comment]
Hey, I checked back and while my code was identical to yours, it seems to have fixed itself. I guess it was a problem on my end. Thanks for the quick response!
