### ISSUE TITLE
[BUG] AIFF text should be treated as UTF-8

### ISSUE THREAD

**Issue by cskau** [devsnd/tinytag#123]
While the [AIFF 1.3 spec](https://web.archive.org/web/20171118222013/http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Docs/AIFF-1.3.pdf) says that text fields "contain pure ASCII characters", it also says:
> A char can contain more than just ASCII characters. It can contain any number from -128 to 127 (inclusive).

And in practice AIFF files are nowadays often tagged with UTF-8 encoded text, rather than simple ASCII.

Trying to load such an AIFF file with TinyTag will currently result in an exception:
```
'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)
```
The encoding is hardcoded here (as well as two more places lower down):
https://github.com/devsnd/tinytag/blob/23bd79d601484856c95b07fdad927191f9203949/tinytag/tinytag.py#L1282

ASCII is however effectively a subset of UTF-8 (i.e. any valid ASCII is also valid UTF-8 by design). So treating these fields as UTF-8 encoded will give exactly the same behaviour for ASCII encoded text, but add support for the (now) much more common UTF-8.

To add support for UTF-8 encoded text fields in AIFF is as simple as changing the three text field loads to:
```python
self.title = self._unpad(chunk.read().decode('UTF-8')) 
```

**Sample File**
An example of an AIFF file with UTF-8 encoded text fields can be found here:
https://chillhop.bandcamp.com/track/velvet

You'll need to click `Digital Track` to download the track in various formats, including AIFF. (Note you can choose to pay 0 to download it for free.)

**Comment by devsnd** [comment]
Hey @cskau ,

I made the changes you suggested and UTF-8 in AIFF is now supported in the master branch. this will be part of the next release.

**Comment by cskau** [comment]
Fantastic! Thanks a lot.
