### ISSUE TITLE
[BUG] Incorrect bitrate and duration for VBR mp3s

### ISSUE THREAD

**Issue by mathiascode** [devsnd/tinytag#124]
**Describe the bug**
tinytag currently returns an incorrect bitrate and duration for several VBR encoded MP3 files, as seen in this screenshot:

![Screenshot from 2021-12-16 07-06-18](https://user-images.githubusercontent.com/8754153/146311644-4117aa5d-d879-4d1b-b169-04f7a3be4796.png)

There seem to be two issues that are causing this:

The number of audio channels is included in this calculation, but it shouldn't be here: https://github.com/devsnd/tinytag/blob/2d6d51b2797565293d17b0029ad03107bceef6a0/tinytag/tinytag.py#L620

If we change the line to `self.duration = xframes * ID3.samples_per_frame / float(self.samplerate)`, the situation improves somewhat:
![](https://user-images.githubusercontent.com/8754153/146310570-05245a6b-dc53-434d-a4f0-9f9bb9dbdb03.png)

There's still another issue that should be addressed in order to retrieve correct info for all files. samples_per_frame is always set to `1152`. This is valid for MPEG-1 Audio Layer III, but the value should be `576` for MPEG-2 Audio Layer III and MPEG-2.5 Audio Layer III (lower sampling rates).

**To Reproduce**
Let tinytag parse the sample files.

**Expected behavior**
tinytag should return the same duration for all attached files, a bitrate of 32 kbps for files with a sampling rate of >=32 khz, and a bitrate of 8 kbps for files with a sampling rate of <32 khz.

**Sample File**
[vbr_samples.zip](https://github.com/devsnd/tinytag/files/7724680/vbr_samples.zip)

**Comment by Foxtrot0711** [comment]
I've noticed the same errror, not only for small files, but for almost every file I tried until now (except for CBR 320)
Bitrate is always double as it should be -> duration is half.
I've tested it with version 1.6 and 1.

[test.zip](https://github.com/devsnd/tinytag/files/7729305/test.zip)
7

**Comment by mathiascode** [comment]
@Foxtrot0711 This branch should fix the issue (for files with Xing headers). Could you check if it works fine with your files? https://github.com/mathiascode/tinytag/tree/vbr-incorrect-duration

I believe files with VBRI headers still have issues, but I haven't looked into that. tinytag reports a bitrate of 125 kb/s for `tinytag/tests/samples/vbri.mp3`, while MediaInfo reports 233 kb/s, but that file seems strange in general.

**Comment by Foxtrot0711** [comment]
works fine.
Thank you!

**Comment by enzanki-ars** [comment]
I just ran into this same issue myself, and testing out that branch also fixed the issue for me.

**Comment by devsnd** [comment]
FYI, I've applied @mathiascode fix to the master branch and will release a new version containing the fix shortly.
