### ISSUE TITLE
[BUG] Some mp3 files report 1/2 of actual duration

### ISSUE THREAD

**Issue by Obliman** [devsnd/tinytag#145]
**Describe the bug**
I have a large list of mp3 files and have noticed that a subset of those files does not have the correct duration from `tag.duration`. It is consistently ~1/2 the real value as reported by the built-in audio player.

**To Reproduce**
Simply load and read the mp3 file duration.

**Sample File**
I retrieved some metadata that I thought was relevant for some example files, shown below. Two have the bug and two do not. I could email files if needed.

HAS BUG:
```
Duration: 107.004
SampleRate: 48000
BitRate: 250.29763373331835
AudioOffset: 501
Extra: {}

Duration: 101.82
SampleRate: 48000
BitRate: 230.9543901001768
AudioOffset: 501
Extra: {}
```

DOES NOT HAVE BUG:
```
Duration: 298.97618113954803
SampleRate: 44100
BitRate: 192.0
AudioOffset: 61972
Extra: {}

Duration: 247.12124390132686
SampleRate: 44100
BitRate: 192.0
AudioOffset: 14445
Extra: {}
```

**Comment by mathiascode** [comment]
I assume you're using tinytag 1.8.1? I could take a look if you email me the files.

**Comment by Obliman** [comment]
Aha... I double checked my tinytag version and it was still 1.8.0. Updating to 1.8.1 fixed the issue.
Thanks for the help.
