### ISSUE TITLE
tag artist, quando adicionado mais de um artista a string fica mal formatada. 

### ISSUE THREAD

**Issue by jamesdean94** [devsnd/tinytag#151]
Identificação em arquivos com extensão .mp3. Podendo se estender para
outros tipos de arquivos.

Bug: mal formatação de string.
Modulo: tinytag.py
Descrição:
Ao inserir mais de um artista na tag artist (artista da faixa) ambos os nomes 
dos artistas ficam juntos. por exemplo: Maria Clara; Karla --> Maria ClaraKarla
No modulo tinytag.py na função _unpad(s) alterei a linha que consta:

     return s.replace('\x00', '') por

     return s.replace('\x00', ' ') *atribuindo um espaço*.

funcionou perfeitamente.

A linha de código substitui o caractere '\x00'  por espaço.

**Comment by devsnd** [comment]
Would you mind posting in english? You can use any web translation service and we'll be able to talk :)
