### ISSUE TITLE
[BUG] Can't read `extra` tags from .m4a files

### ISSUE THREAD

**Issue by kylelambert101** [devsnd/tinytag#166]
**Describe the bug**
I added a custom field (via mp3tag) to audio files of various types, but that custom field only appears in tinytag's `extra` collection for the mp3 files and not the m4a files. 

**To Reproduce**
1. Unzip the Songs.zip attachment to find two files - both have a custom tag called `KPL_DATE` with the value `TEST_DATE`
2. Dump the tags for the two contained files using tinytag: `python3 -m tinytag --format json Symphony1.m4a Symphony2.mp3`
3. See that the custom tag is listed in `extra` for the mp3 file but not for the m4a file.  
<img width="548" alt="image" src="https://user-images.githubusercontent.com/19976093/205199217-c8ea2c3c-a67b-474b-b85a-859547ec015e.png">

**Expected behavior**
The custom tag is listed under `extra` for both files

**Sample File**
[Songs.zip](https://github.com/devsnd/tinytag/files/10137371/Songs.zip)

**Comment by mathiascode** [comment]
Support for extra tags from m4a files has not been implemented yet.
