### ISSUE TITLE
Expose a list of supported file extensions

### ISSUE THREAD

**Issue by mungai-njoroge** [devsnd/tinytag#167]
**Is your feature request related to a problem? Please describe.**
I'm using [watchdog](https://pypi.org/project/watchdog/) to watch for music file changes in the file system. I am currently passing a list of file extensions that should trigger events like this:

```py
...

PatternMatchingEventHandler.__init__(
    ...
    patterns=["*.flac", "*.mp3"],
    ...
)

...
```
I want to trigger events for all files that are supported by TinyTag. Can you expose a list or set of supported file extension that we can use for this purpose? I have checked  #53 and the solution there does not work for this specific problem.

**Describe the solution you'd like**
A simple list of supported formats. For example:

```py
>>> TinyTag.SUPPORTED_EXTENSIONS
[".mp4", ".mp3", ".flac", ...]
```

**Comment by mathiascode** [comment]
Should the extensions start with a period or not? I'm wondering which format would be more useful and easier to work with in most cases.

**Comment by geoffrey45** [comment]
The period needs to be there. I think mose use cases require the period.

... and thank you for this 🙏

**Comment by slook** [comment]
`mapping` in `_get_parser_for_filename()` could perhaps be adapted into a constant for this purpose:

https://github.com/devsnd/tinytag/blob/27b26ce25cfd44b6fb7c6da82177d725c07a2ab9/tinytag/tinytag.py#L127-L135
