### ISSUE TITLE
[BUG] Incompatibility with Python-pip

### ISSUE THREAD

**Issue by Prakash4844** [devsnd/tinytag#175]
**Describe the bug**
Tinytag fails to install through Python-pip.

Seems to happen because tinytag lists pip>=10 as a setup dependency.

pip has been >= 10 for a long time, so just removing that dependency and then installing works fine:

```bash
git clone https://github.com/devsnd/tinytag
cd tinytag
sed -i 's%  pip >= 10%%g' setup.cfg
pip install .
```

**To Reproduce**
1. in Termux, Install Python using `pkg install python`, it will also install python-pip 
2. run command `pip install tinytag`

**Expected behavior**
Tinytag installed Successfully.

**Sample File**
Log can be found here [Python-pip log for tinytag](https://pastebin.com/nJW1L5hX)

**Comment by mathiascode** [comment]
Thanks for reporting this, I'll tag a 1.9.1 release of tinytag in a few days.

**Comment by Prakash4844** [comment]
Thanks.
