### ISSUE TITLE
[BUG] `tags.year` is null although the MP3 file has the year set

### ISSUE THREAD

**Issue by mungai-njoroge** [devsnd/tinytag#179]
**Describe the bug**
I'm getting a null on the year tag for some of my mp3s. The tags can be read using music players, eg. Audacious.

I've attached a sample file.

**Sample File**
[African Giant CD 1 TRACK 2 (320).zip](https://github.com/devsnd/tinytag/files/12215455/African.Giant.CD.1.TRACK.2.320.zip)

**Comment by mathiascode** [comment]
Are you using tinytag 1.9.0? The year appears for me.

**Comment by mungai-njoroge** [comment]
Ahaa ... I was using `tinytag = "^1.8.1"`. Updating to `1.9.0`worked.

Thanks.
