### ISSUE TITLE
m4a/mp4 support

### ISSUE THREAD

**Issue by systems-rebooter** [devsnd/tinytag#18]
Hey @devsnd, 

Can you add m4a / mp4 support to tiny?

**Comment by lesthack** [comment]
+1

**Comment by devsnd** [comment]
MP4 support is mostly implemented in the feature/mp4 branch. Not all mp4 files are working so this isn't merged into the master yet...

https://github.com/devsnd/tinytag/tree/feature/mp4

**Comment by systems-rebooter** [comment]
Great! Welcome back! :]
