### ISSUE TITLE
[BUG] tinytag 1.10.0 aiff does not have extra data

### ISSUE THREAD

**Issue by aw-was-here** [devsnd/tinytag#187]
**Describe the bug**
AIFF support appears to be broken with regards to extra data in 1.10.0. TinyTag 1.0.9 properly pulls out fields like `isrc` whereas 1.10.0 does not.

**Expected behavior**
Data parity

**Sample File**
https://github.com/whatsnowplaying/whats-now-playing/blob/4.1.0/tests/audio/15_Ghosts_II_64kb_f%C3%BCllyt%C3%A2gged.aiff

**Comment by mathiascode** [comment]
Most likely a regression in https://github.com/devsnd/tinytag/commit/b6bb7ed43b643190dfb06fff8aac559a6f0cae50. We're missing aiff files with extra ID3 tags in our tests.

**Comment by mathiascode** [comment]
Could you verify that the master branch works fine? If so, I'll tag a 1.10.1 release as soon as possible.

**Comment by aw-was-here** [comment]
From my testing, things appear to be working again. Thanks!

**Comment by mathiascode** [comment]
1.10.1 has been released. Thanks for reporting the issue!
