### ISSUE TITLE
Ability to get all images

### ISSUE THREAD

**Issue by aw-was-here** [devsnd/tinytag#189]
I would like the ability to get all of the images in a file.  Currently, I think tinytag is coded to just pull the cover image or maybe it is the first image it comes across.  Ideally, I'd like to have each image and its location (e.g., cover, insert, etc) accessible.

Thanks!

**Comment by mathiascode** [comment]
What would the ideal API for this look like? I'm thinking something similar to the `extra` dict could work here, with standardized keys and image data as the value, but are we missing any important information this way? Is there anything else than the image and its description that's important to retain?

**Comment by aw-was-here** [comment]
I can't think of any other info that would be useful that would be in the purview of TinyTag. e.g., image size, image type, etc, are better handled by something like Pillow and would need to be handled by the downstream caller anyway.

**Comment by aw-was-here** [comment]
> mime_type and picture_type are included because ID3 provides them, but I haven't looked into what other formats do.

I wonder how reliable those fields actually are.  In my particular case I'll likely just pass the raw data to pillow to convert to a known format.

**Comment by mathiascode** [comment]
PR for testing: https://github.com/devsnd/tinytag/pull/202

I changed my mind and used classes instead of dictionaries. Allows you to easily access images as such:
```
image = tag.images.front_cover
data = image.data
description = image.description
```

> I wonder how reliable those fields actually are. In my particular case I'll likely just pass the raw data to pillow to convert to a known format.

I haven't had time to look into them, so I left them out for now. The format allows us to easily expose them in the future though, if necessary.

**Comment by mathiascode** [comment]
The image MIME type is now available under `tag.images.front_cover.mime_type`.

**Comment by mathiascode** [comment]
I didn't think about the case where multiple images of the same kind can exist, so the API has been changed. You can check the README.md file for more details, but it essentially boils down to:

- `tag.images.any` to get any image available, prioritizing the cover art. `tag.images.any.data` to get the image as bytes.
- 'images' attributes now contain lists of images. If you want to e.g. get a list of leaflet images, you can do so with `tag.images.leaflet`. To get the first leaflet image, `tag.images.leaflet[0]`.
- More uncommon image types were moved to `tag.images.extra`. If you want to get e.g. a list of artist images, `tag.images.extra.get('artist')`.

**Comment by aw-was-here** [comment]
OK I'll try to make some time today/tomorrow to play around with this feature and see how it works out in my workflow.  Thanks again!

**Comment by aw-was-here** [comment]
Sorry @mathiascode I got distracted with some family stuff. This one is back on my radar and I'll try it out.

**Comment by aw-was-here** [comment]
The new code seems to be working ok for me with some quick, preliminary tests.  Got a [track with 9 front_cover images](https://musicbrainz.org/release/29cc7eff-fd8b-4cee-89a2-f36c923086f7/cover-art) and I'm getting the proper data for all 9.

Great job! Thanks!
