### ISSUE TITLE
[BUG] only get the first artist in multiple when read flac file

### ISSUE THREAD

**Issue by NingmengLemon** [devsnd/tinytag#192]
When I tried reading tags from a flac file, tinytag only got the first artist out of 3 artists.  

```python
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tinytag import TinyTag
>>> print(TinyTag.get("E:\samples\ひだまりデイズ.flac").artist)
田中あいみ
# it should be 田中あいみ and 影山灯 and 白石晴香 and 古川由利奈
```

emm this problem did not happen on my other flac files, artist tags in these files are separated by `/` (though I think it's incorrect) 
```python
>>> print(TinyTag.get("E:\samples\ひとりじゃイヤ (feat. 初音ミク).flac").artist)
みつあくま/初音ミク
```

view in Mp3Tag:

other files be like: 
![image](https://github.com/devsnd/tinytag/assets/60469383/c73031a1-2ca6-404d-971d-27c27035514b)

this file be like: 
![image](https://github.com/devsnd/tinytag/assets/60469383/544f2bec-4996-4e7f-93a7-ff3d7a90328f) 

view in foobar2000: 

other files: 
![image](https://github.com/devsnd/tinytag/assets/60469383/20a9341a-524d-4c66-8fd9-290180b179dc)

this file: 
![image](https://github.com/devsnd/tinytag/assets/60469383/d2ffdd0f-3eba-401a-82ba-f1f224ac3398)

sample files here: https://drive.google.com/drive/folders/1urwlLSFWxv3y7jvQ7fEHYaZhUoR2kusT?usp=drive_link

sorry for poor eng （＞人＜；）

**Comment by mathiascode** [comment]
Thanks for reporting this issue.

Would the changes in https://github.com/devsnd/tinytag/pull/193 work for you? Artists are separated with a null character (`\x00`), so you could either split the string, or replace the character with a separator of your choice.

**Comment by NingmengLemon** [comment]
> Thanks for reporting this issue.
> 
> Would the changes in #193 work for you? Artists are separated with a null character (`\x00`), so you could either split the string, or replace the character with a separator of your choice.


Thank you sir!  
I downloaded the newest code and tried again, sorry but...  
It seems that, there's no change?   
```python
>>> TinyTag.get("E:\samples\ひだまりデイズ.flac").artist
'田中あいみ'
```
As you can see, tinytag only got the first artist?
(however this file has 4 artists in fact)  
Is the way I use tinytag wrong?

**Comment by mathiascode** [comment]
> As you can see, tinytag only got the first artist? (however this file has 4 artists in fact) Is the way I use tinytag wrong?

No, it's correct, but the new code wasn't merged yet. Try the latest master and let me know how it works for you.

**Comment by NingmengLemon** [comment]
> > As you can see, tinytag only got the first artist? (however this file has 4 artists in fact) Is the way I use tinytag wrong?
> 
> No, it's correct, but the new code wasn't merged yet. Try the latest master and let me know how it works for you.

It works! Thank you so much
```python
>>> TinyTag.get("E:\samples\ひだまりデイズ.flac").artist
'田中あいみ\x00影山灯\x00白石晴香\x00古川由利奈'
```

**Comment by mathiascode** [comment]
You're welcome! It was a good opportunity to do some work on this library again. :)

**Comment by mathiascode** [comment]
The API was changed to make it more predictable:
- The first artist is stored in `tag.artist`, as previously
- Any additional artists are added to the `tag.extra.other_artists` list

**Comment by NingmengLemon** [comment]
> The API was changed to make it more predictable:
> 
> * The first artist is stored in `tag.artist`, as previously
> * Any additional artists are added to the `tag.extra.other_artists` list

It's great to see this project continue to progress! I will also adapt my program to this change, and thank you again for your work (´▽`ʃ♡ƪ)
