### ISSUE TITLE
[BUG] tinytag does not support certain non-ascii filenames

### ISSUE THREAD

**Issue by aw-was-here** [devsnd/tinytag#205]
**Describe the bug**
When processing filenames, if it is not ascii, it will blow up.

**To Reproduce**

1. Create a file called `15_Ghosts_II_64kb_füllytâgged.mp3`
2. Attempt to read it into TinyTag
3. Get an exception:

```
ERROR    root:metadata.py:72     tag = tinytag.TinyTag.get(self.metadata['filename'], image=True)
ERROR    root:metadata.py:72           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR    root:metadata.py:72   File "/Users/aw/Src/whats-now-playing/nowplaying/vendor/tinytag/tinytag.py", line 132, in get
ERROR    root:metadata.py:72     parser_class = cls._get_parser_class(filename, file_obj)
ERROR    root:metadata.py:72                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR    root:metadata.py:72   File "/Users/aw/Src/whats-now-playing/nowplaying/vendor/tinytag/tinytag.py", line 216, in _get_parser_class
ERROR    root:metadata.py:72     parser_class = cls._get_parser_for_filename(filename)
ERROR    root:metadata.py:72                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR    root:metadata.py:72   File "/Users/aw/Src/whats-now-playing/nowplaying/vendor/tinytag/tinytag.py", line 174, in _get_parser_for_filename
ERROR    root:metadata.py:72     filename_bytes = filename.encode('ascii')
ERROR    root:metadata.py:72                      ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR    root:metadata.py:72 UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 63: ordinal not in range(128)
```

**Expected behavior**
It should not exception

**Sample File**
From my source tree: https://github.com/whatsnowplaying/whats-now-playing/blob/main/tests/audio/15_Ghosts_II_64kb_f%C3%BCllyt%C3%A2gged.mp3  (there are others there as well)

=========

The problem is obviously [here](https://github.com/devsnd/tinytag/blob/2ca8431852db154b3f20336204770a07ce8ec9fa/tinytag/tinytag.py#L174) and it is trivial to change it to UTF-8.  I'm suspecting this one is a hold over from Python 2.7 support that just needs to get whacked for 2.0.  Filing the issue to verify that and also wondering if there are some other hidden Python 2-isms that should probably get a closer look.

**Comment by mathiascode** [comment]
> The problem is obviously [here](https://github.com/devsnd/tinytag/blob/2ca8431852db154b3f20336204770a07ce8ec9fa/tinytag/tinytag.py#L174) and it is trivial to change it to UTF-8. I'm suspecting this one is a hold over from Python 2.7 support that just needs to get whacked for 2.0. Filing the issue to verify that and also wondering if there are some other hidden Python 2-isms that should probably get a closer look.

The 'errors' argument for encode() was removed by mistake in a recent commit, but using os.fsdecode() is a cleaner solution.

I've removed all Python 2-isms I noticed.
