### ISSUE TITLE
Speed up TinyTag with MP3 processing

### ISSUE THREAD

**Issue by andpp** [devsnd/tinytag#21]
As you propose, we continue our discussion here.
@devsnd "Maybe we could add the following ability to TinyTag: If there are e.g. 5 consecutive frames with the same bitrate, we assume it's CBR and stop."

This is the way mp3info works with CBR MP3 files. And I have to change the way mp3info calculates the play time because nether TinyTag nor mp3info cannot calculate correct time for my 22050/mono MP3 files. Both give me about two times less than actual play time though JPlayer show the correct play time. That's why I started to look for another library to calculate the play time.

**Comment by devsnd** [comment]
Can you please provide the mono mp3 you've been using? I added a 22khz mono mp3 to the test suite and it worked for me.

**Comment by devsnd** [comment]
Hey Andrey,

I have improved tinytag to stop after 5 consectutive frames and then assume that it's CBR. (This might go wrong for some tracks with a very quiet intro, so we should test this a bit more before I release this as a new version). This makes tinytag about 5 to 6 times faster than mp3info for CBR tracks and as fast as mp3info for VBR tracks.

Also tinytag is now more accurate than before (and also more accurate than mp3info in my tests) when determining the duration of a mp3 file.

You can just drop the tinytag.py from this repository into cherrymusic to try it out.

**Comment by andpp** [comment]
Hi Tom!

  I tried your new version. I still get wrong time. Here is my records. Could you try it.   https://drive.google.com/folderview?id=0B-rCqP_KhU_CWlBLUi0xRTFXYkk&usp=sharing

**Comment by devsnd** [comment]
Hey Andrey,

It took me some time to get back to this, but now I've implemented support for all mpeg versions and layers and furthermore correctly calculate all sample rates and bitrates for each combination.

If you try the newest version of tinytag, you should get correct time readings now. I still have to make a new version and update it in cherrymusic, but my tests work fine for the at least one of the files you provided. Thanks again for the samples!

**Comment by devsnd** [comment]
Closing: TinyTag now supports the Xing header and is as fast as other parsers.
