### ISSUE TITLE
Change DEBUG global name

### ISSUE THREAD

**Issue by amirhoseinbidar** [devsnd/tinytag#210]
Based on experience DEBUG environment variable is being used a lot in application debugging. For example in Django. As a result, when developers are debugging their applications, they turn on TinyTag debug mode accidentally. I recommend using another environment variable name like TINYTAG_DEBUG to avoid accidents like this.
Best Regards.

**Comment by mathiascode** [comment]
Thanks for the suggestion. The new environment variable is `TINYTAG_DEBUG`.
