### ISSUE TITLE
found (and fixed) a bug in the _set_field function

### ISSUE THREAD

**Issue by domingobernardo** [devsnd/tinytag#30]
This is my first time using tinytag
I have a collection of 75000 mp3s
Turns out that one of the files had 1/4/4/4/4/4 stored in the "disc" tag
which made _set_field crash

If you change the lines from 
               current, total = str(value).split('/')  #which of course only works if the value is xx/xx 

to this:
                splits = str(value).split('/')
                current, total = splits[0], splits[1]

it will work every time

**Comment by devsnd** [comment]
hey Domingo!

thanks a lot for your report and fix. before I include this fix in tiny tag, I'd like to be sure that the data is valid in this case. so are the first two numbers of the 4/4/4/4 really the indicator that this track is on the 4th disc of 4, or is it indeed wrong information?

tom

**Comment by domingobernardo** [comment]
It should be disc 1 of 4 ; like this 1/4
but someone changed it to 1/4/4/4/4/4/4



On Mon, Mar 28, 2016 at 4:01 AM, Tom Wallroth <notifications@github.com>
wrote:

> hey Domingo!
>
> thanks a lot for your report and fix. before I include this fix in tiny
> tag, I'd like to be sure that the data is valid in this case. so are the
> first two numbers of the 4/4/4/4 really the indicator that this track is on
> the 4th disc of 4, or is it indeed wrong information?
>
> tom
>
> On March 28, 2016 7:03:37 AM CEST, domingobernardo <
> notifications@github.com> wrote:
> >This is my first time using tinytag
> >I have a collection of 75000 mp3s
> >Turns out that one of the files had 1/4/4/4/4/4 stored in the "disc"
> >tag
> >which made _set_field crash
> >
> >If you change the lines from
> >current, total = str(value).split('/') #which of course only works if
> >the value is xx/xx
> >
> >to this:
> > splits = str(value).split('/')
> > current, total = splits[0], splits[1]
> >
> >it will work every time
> >
> >
> >
> >---
> >You are receiving this because you are subscribed to this thread.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/devsnd/tinytag/issues/30
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/devsnd/tinytag/issues/30#issuecomment-202291451>
>



-- 
Domingo "Chip" Bernardo
Okeechobee, Florida, USA
Orotina, Alajuela, Costa Rica

**Comment by domingobernardo** [comment]
Dear Tom,
I setup a logger in tinytag and ran it with another collection that had
79,000 files
The errors are logged in the attached file (assuming github will accept an
attached file)

I don't know enough about the file formats to understand what exactly is
causing the error, otherwise I would gladly offer a solution

Domingo

On Tue, Mar 29, 2016 at 2:37 PM, Domingo Bernardo <
domingopbernardo@gmail.com> wrote:

> It should be disc 1 of 4 ; like this 1/4
> but someone changed it to 1/4/4/4/4/4/4
>
>
>
> On Mon, Mar 28, 2016 at 4:01 AM, Tom Wallroth <notifications@github.com>
> wrote:
>
>> hey Domingo!
>>
>> thanks a lot for your report and fix. before I include this fix in tiny
>> tag, I'd like to be sure that the data is valid in this case. so are the
>> first two numbers of the 4/4/4/4 really the indicator that this track is on
>> the 4th disc of 4, or is it indeed wrong information?
>>
>> tom
>>
>> On March 28, 2016 7:03:37 AM CEST, domingobernardo <
>> notifications@github.com> wrote:
>> >This is my first time using tinytag
>> >I have a collection of 75000 mp3s
>> >Turns out that one of the files had 1/4/4/4/4/4 stored in the "disc"
>> >tag
>> >which made _set_field crash
>> >
>> >If you change the lines from
>> >current, total = str(value).split('/') #which of course only works if
>> >the value is xx/xx
>> >
>> >to this:
>> > splits = str(value).split('/')
>> > current, total = splits[0], splits[1]
>> >
>> >it will work every time
>> >
>> >
>> >
>> >---
>> >You are receiving this because you are subscribed to this thread.
>> >Reply to this email directly or view it on GitHub:
>> >https://github.com/devsnd/tinytag/issues/30
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/devsnd/tinytag/issues/30#issuecomment-202291451>
>>
>
>
>
> --
> Domingo "Chip" Bernardo
> Okeechobee, Florida, USA
> Orotina, Alajuela, Costa Rica
>
>
>
>


-- 
Domingo "Chip" Bernardo
Okeechobee, Florida, USA
Orotina, Alajuela, Costa Rica

**Comment by devsnd** [comment]
Hey Domingo,

You attachment does not see to have arrived... Could you please upload the log to pastebin or something?

tom

**Comment by devsnd** [comment]
I have fixed the initial bug. I will release another version of tinytag later this day!

**Comment by domingobernardo** [comment]
Ok
Will do

-----Original Message-----

**Comment by domingobernardo** [comment]
Awesome 

-----Original Message-----

**Comment by domingobernardo** [comment]
Dear Tom,

Try looking here for the log file:
https://drive.google.com/open?id=0B06Jnn025RCcNVlXbGVCbncxWGM

if github breaks that up
https
drive.google.com
open?id=
0B06Jnn025RCcNVlXbGVCbncxWGM

On Sat, Apr 2, 2016 at 11:06 AM, Tom Wallroth <notifications@github.com>
wrote:

> Hey Domingo,
>
> You attachment does not see to have arrived... Could you please upload the
> log to pastebin or something?
>
> tom
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/devsnd/tinytag/issues/30#issuecomment-204731155>
>



-- 
Domingo "Chip" Bernardo
Okeechobee, Florida, USA
Orotina, Alajuela, Costa Rica

**Comment by devsnd** [comment]
Thanks for the log, Domingo!

BTW: I released a new version with includes the fix (0.13.1) for this one problem.

The entries in your log seem to show some errors that occur when the files contain an invalid sample_rate for a certain mpeg versions etc. Some of those errors I can fix using the information from the log, other however not.

I will try to reproduce these errors in my music collection, but it is not guaranteed that the same erros will occur.
Is it okay for you if you sent me some of those files? Maybe we can do this via mail. Please contact me at tomwallroth [aŧ] gmail [døt] com, if you are willing to help me any further!
