### ISSUE TITLE
Can't get cover art from mp3 files with ID3 v2.2

### ISSUE THREAD

**Issue by Timetopretend** [devsnd/tinytag#36]
Hi,

I can't get the cover art of few audio files.
The get_image () method does not detect. I can provide the file by e-mail
Otherwise I want to **thank you** for this library, very efficient and convenient. (I have made some benchmarks tests against others and this one is very fast)

Email sent to tomwallroth ...

**Comment by devsnd** [comment]
Hey Rc,

I've received the files and also found the culprit; TinyTag is not yet capable of parsing image from ID3 v2.2 tags. I'm on it :penguin:

**Comment by Timetopretend** [comment]
Great, I will follow it closely. :+1:

**Comment by devsnd** [comment]
Hey @Timetopretend,

I have implemented the changes necessary to parse your mp3 files and to read images from ID3v2.2.

But only one of the two samples you provided actually contained an image (GCCH.mp3), this other (QJWS.mp3) did not, not only according to my analysis, but also according to VLC.

The file does not contain any JPEG data:

    grep JFIF ./QJWS.mp3

Anyway, thanks for your report and the praise! :chicken: :children_crossing: I have released a new version 0.17.0 to pypi, so you can install it via pip.

Have a nice day :cake:

**Comment by Timetopretend** [comment]
So fast ! 
Oddly, Vlc shows me a picture to the second file... I will investigate !
I'll do the update immediately

Have a nice day ! :sun_with_face:
