### ISSUE TITLE
bitrate is in bps (not kbps) for VBR mp3 files

### ISSUE THREAD

**Issue by AntiSol** [devsnd/tinytag#39]
Hi,

Any VBR mp3 file I point tinytag at gives me a bitrate value which is about 1000x what audio software reports. I expect that this value is bps rather than kbps.

For example, for the file at (https antisol dot org slash brass dot mp3), tinytag gives me a bitrate value of 195206.785168, whereas various audio software reports the file as being 195kbps, including:
* audacious
* qmmp
* vlc ('input bitrate' on 'statistics' screen lists ~195kbps, but codec info tab shows 128kbps)

I've seen this with all other VBR mp3 files I've tried, they all give a value ~1000x the value reported by audacious.

As a workaround I was able to do something like:
````python
if bitrate > 320: bitrate = bitrate / 1099
````
to get a pretty good bitrate value. But it would be nice to see a more accurate value come from TinyTag.

Thanks!

**Comment by devsnd** [comment]
Hey Dale,

Thanks for your report! Could you please provide a sample (upload it somewhere or send it to my email tomwallroth [aŧ] gmail [døt] com)that shows this issue so I can fix it and also include the fix into the test suite? I will only get around to do this on the weekend however.

**Comment by AntiSol** [comment]
````python
from tinytag import TinyTag
fn="brass.mp3"
i = TinyTag.get(fn)
print "bitrate: %s" % i.bitrate
if i.bitrate > 320: 
	i.bitrate = i.bitrate / 1000
	print "Corrected bitrate: %s" % i.bitrate
````

brass.mp3 is the file i linked to in my report. The output will be "bitrate: 195206.785168", where the reported bitrate should be ~195.

Also note that in the code I provided in my bug report, "1099" should be "1000"

**Comment by AntiSol** [comment]
Also note that using "bitrate > 320" is not ideal and may not work for all codecs, e.g FLAC is probably encoded at a higher bitrate. I used 320 because it's the highest bitrate you see on MP3 files. A better test would be to check if the file is VBR.

**Comment by devsnd** [comment]
Hey Dale,

you're right, I just reproduced the issue. I'm looking into it right now.

**Comment by AntiSol** [comment]
brilliant, thanks! :)

**Comment by devsnd** [comment]
Hey Dale,

I have fixed the problem, thanks again for your bug report! I will release a new version containing the fix right away, but you can always use the master branch here.
If find any other issues let me know.

Have a nice day and you can also keep this toy car 🚗

**Comment by AntiSol** [comment]
Confirmed fixed. Awesome. Thanks so much for dealing with this so quickly - very impressive :)
