### ISSUE TITLE
ZeroDivisionError when duration is 0

### ISSUE THREAD

**Issue by re1** [devsnd/tinytag#40]
Got a ZeroDivisionError while processing this:
```
self.duration = xframes * ID3.samples_per_frame / float(self.samplerate)
                        self.bitrate = byte_count * 8 / self.duration
```

Traceback can be found here:
``` python
tag = TinyTag.get("music.mp3")

File "/usr/lib/python3.6/site-packages/tinytag/tinytag.py", line 136, in load self._determine_duration(self._filehandler)

File "/usr/lib/python3.6/site-packages/tinytag/tinytag.py", line 528, in _determine_duration
self.bitrate = byte_count * 8 / self.duration

ZeroDivisionError: float division by zero
```

You may want to add some error-handling to avoid compatibility problems, I can fix it for you if you want to.

**Comment by devsnd** [comment]
Thanks for your report!

Feel free to make PR if you have the time. As I am really busy right now, I can only take a look at it on the weekend!

**Comment by devsnd** [comment]
Fixed by https://github.com/devsnd/tinytag/pull/41
