### ISSUE TITLE
Is it Possible to change Tags and Album art?

### ISSUE THREAD

**Issue by YuganshT79** [devsnd/tinytag#43]
Can i edit the tags of media file , 
and also edit ID3v2 tags so that they show up in Windows media player??

**Comment by devsnd** [comment]
Hey @YuganshT79 sorry, I seem to have missed the notitication for this issue!

Anyway, unfortunately I must disappoint you twice: TinyTag is and will stay a read-only tool. If you want to change tags, there are other, bigger and more complex libraries to do so. e.g. eyeD3
