### ISSUE TITLE
How to get the Codec ?

### ISSUE THREAD

**Issue by lbrth** [devsnd/tinytag#44]
Hi,

I would like to extract the codec of the music files (mp3, FLAC, ...). The main objectif if to compare all tracks each other to find duplicates and keep the tracks with the best quality.

How I could procede to get the info ?

Thanks,

lbrth

**Comment by devsnd** [comment]
Hey Ibrth,

Here's some example code to get you going. I didn't try it out, so there might be a small mistake,  but I'm sure you'll get it to work. This code will look in all directories below `/some/dir/path` and collect artist and titles from all mp3s and flacs. Afterwards it will output all the tracks that have the same artist and name and their file locations. Note that even the smallest differences will make that the artists and titles don't match, e.g. "James Brown" and "james brown" will not be picked up as the same artist. This you will have to figure out yourself.

    from collections import defaultdict
    import os

    music_files = defaultdict(list)
    music_path = '/some/dir/path'

    for dirpath, dirnames, filenames in os.walk(music_path):
        for filename in filenames:
            # only look at flacs and mp3s
            if not filename.endswith(('.mp3'), ('.flac')):
                continue
            full_file_name = os.path.join(dirpath, filename)
            tag = TinyTag.get(full_file_name)
            # collect all tracks with the same artiest and name in a list
            track_identifier = (tag.artist, tag.title)
            music_files[track_identifier].append(full_file_name)

    # find tracks that exist multiple times
    for identifier, filepaths in music_files.items():
        if len(filepaths) > 1:
            print('There are multiple versions of %s' % identifier)
            for filepath in filepaths:
                print(filepath)

I hope that this is of any help to you. For further questions, I guess you should ask on stackoverflow.

**Comment by lbrth** [comment]
Hi @devsnd ,

Thank's a lot for your very helpful reply. To get the codec I did exactly the same thing (get the file extension) but I didn't know the "collections" library, seems to be very powerful, I'm going to win some time with it for the deduplication process  ! For the case where the filename doesn't match exactly, my idea is to normalize all file name as upper case and delete special charactere to compare it.  

Thanks again for your disponibility,

lbrth
