### ISSUE TITLE
TinyTag gives None for tags generated by Windows Media Player rip

### ISSUE THREAD

**Issue by dospunk** [devsnd/tinytag#51]
I'm trying to get the tags of some Wave files ripped from a CD through Windows Media Player, but tinytag is giving `None` for all the tags. If I try to add tags to the files manually with Audacity, I get `struct error: unpack requires a buffer of 10 bytes`. Other Wave files converted from mp3 and tagged using Audacity work fine.

**Comment by dospunk** [comment]
**Update on what I've found:**

The 10 bytes needed error was caused by Audacity adding an extra empty byte at the end of the file.

The `None` tags error is caused by Windows Media Player not adding the tags in ID3 format, but rather the old LIST format at the beginning of the file

**Comment by headrx** [comment]
Was this ever fixed ??

**Comment by devsnd** [comment]
Probably not. Without a sample file that shows the issue there's nit much i
can do.

So please provide a sample an reopen the issue if this is still a valid bug
report
