### ISSUE TITLE
Request: provide a method that returns all supported formats

### ISSUE THREAD

**Issue by ehudkaldor** [devsnd/tinytag#53]
I'm looking for my application to do a conditional like:

> if not file.split(".")[-1].lower() in TinyTag.getSupportedTypes():

essentially, to check programmatically if a file extension is supported before trying to parse metadata. it would help for future changes...

**Comment by devsnd** [comment]
Hey @ehudkaldor,

excellent suggestion, I will add this to the next release. (You will be notified in this issue when it's implemented in the master branch)

**Comment by devsnd** [comment]
Hey @ehudkaldor 

There is now a `TinyTag.is_supported(filename)` method, that you can use!
