### ISSUE TITLE
REQUEST:  Support for m4b files?

### ISSUE THREAD

**Issue by doc-jay** [devsnd/tinytag#54]
Any chance of adding support for m4b files?

thanks!

**Comment by devsnd** [comment]
Hey doc,

I had never heard of m4b and after a quick search, it seems its practically
equivalent with m4a.

So please do me a favor and rename obe of your m4b files to m4a; if it
works, i will add the support for the m4b extension!

**Comment by doc-jay** [comment]
sure thing

**Comment by doc-jay** [comment]
Yep – that worked perfectly.  I’ve updated the issue with my comments.

 

Thanks!

**Comment by devsnd** [comment]
Hey doc-jay,

In the git version tinytag will now automatically use the MP4 parser for m4b files. It will also be in the next release (0.21.0) which will be released soon.
