### ISSUE TITLE
Example for saving album art to a local file

### ISSUE THREAD

**Issue by NaturalFigurehead** [devsnd/tinytag#58]
Is there an example I could use for saving album art to a local file? I'm doing this:
```
tag = TinyTag.get(filePath, image=True)
    image_data = tag.get_image()

with open(filePath + '.jpg', "wb") as f:
    f.write(image_data)
```
But then I get a jpg file that can't be opened.

**Comment by candh** [comment]
This example of yours works fine. (Just remove the indent on line 2), But only in version 0.19.0 (see [#45](https://github.com/devsnd/tinytag/issues/45)) which hasn't been pushed to pypi (idk why). You have to pull the latest changes and install that. 

Also, be careful of the extension you're appending to the filename. The image byte data contains a header that specify which type of format it is. So you might want to save in that format.

**Comment by NaturalFigurehead** [comment]
Cool it's working after just including the raw tinytag.py file from the repo. 

I was wondering how to determine the file type. How do you extract that header information?

**Comment by candh** [comment]
You can use Pillow:
```python
from io import BytesIO
from PIL import Image

filePath = '...path'
tag = TinyTag.get(filePath, image=True)
image_data = tag.get_image()

image = Image.open(BytesIO(image_data))
print(image.format)
# or you can use
print(image.get_format_mimetype())
```
or you can compare the first few bytes with all these headers to check which file you have
```python
JPEG = "\xFF\xD8\xFF"
GIF  = "GIF"
PNG  = "\x89\x50\x4e\x47\x0d\x0a\x1a\x0a"
BMP  = "BM"
PSD  = "8BPS"
SWF  = "FWS"
```
[copied from here](https://stackoverflow.com/questions/3312607/php-binary-image-data-checking-the-image-type)

**Comment by NaturalFigurehead** [comment]
@candh 
sweet, everything's working now. Thanks
