### ISSUE TITLE
Hangs when parsing of a specific wav file (getting duration)

### ISSUE THREAD

**Issue by ianhomer** [devsnd/tinytag#65]
I have particular wav file (don't have rights to share though sorry), but when I load with TinyTag the process hangs.

Digging it issue I see that the process is stuck in a loop of scanning the file. I have a fix prepared and I will share branch for consideration.

**Comment by devsnd** [comment]
Thanks again for your efforts! It's really appreciated. Give me a bit to release a new version, until then you'll have to use the `master` here from github in your requirements.
