### ISSUE TITLE
Binary paths are not handled

### ISSUE THREAD

**Issue by jfu334** [devsnd/tinytag#72]
It seems that the python spec allows pathes to be either strings or binary data. According to stackoverflow this is cause on linux, filenames do not have an encoding but are just a buch of bytes. 

In my case, I have a path that is *not* UTF-8 and converting it to an UTF-8 string does not work cause the conversion fails with encoding errors.

Using the os functions (ie. os.stat) to access the file through its binary name works. (like ``os.stat(b"some\x12nasty\x34file\xff")``)

However TinyTag fails to access the file. This is caused by tinytag.py line 122:
``filename = os.path.expanduser(str(filename))  # cast pathlib.Path to str``

In the light of how pathes work on linux, casting to str is obviously the wrong way.

**Comment by devsnd** [comment]
Hey @jfu334 

This problem is now fixed in the `master` branch. I will release a new version soon which contains the fix as well.
