### ISSUE TITLE
Add an option to ignore encoding errors

### ISSUE THREAD

**Issue by jfu334** [devsnd/tinytag#73]
Currently TinyTag fails if it can't decode a string. (line 664, _decode_string)

However when parsing existing data, it happens sometimes that someone wrote garbage into the tags data field. It should be possible to ignore the garbage.

**Comment by devsnd** [comment]
Hey @jfu334 can you please provide a sample file?

**Comment by jfu334** [comment]
Sorry can't post the file here. However while working through my mp3 lib, I've discovered numerous weird or strange tags. One software for example wrote a terminating 0 byte at the end of all strings. 

It should be possible to work with such incorrect data as good as possible.

**Comment by devsnd** [comment]
Hey, this has been addressed in version 1.3.1

have a nice day, and a piece of cake, if you feel like it, of course :cake:
