### ISSUE TITLE
genre of some .mp3 files being shown as "None" when they are not

### ISSUE THREAD

**Issue by NitishaS-812k** [devsnd/tinytag#80]
I have attached the link for one such file, I used ID3 and obtained the genre to be "Pop",  I also used Rhthymbox to see the metadata of the file and there too the genre was "Pop". However, upon using Tiny Tag, I obtain the genre to be "None".
**output as obtained from eyed3/ID3:**
>>> from eyed3 import id3
>>> tag = id3.Tag()
>>> tag.parse("/media/nitisha/4858-8C4E/Music/Applause.mp3")
True
>>> print(tag.genre)
(13)Pop

**output as obtained from tinytag:**
>>> from tinytag import TinyTag
>>> tag = TinyTag.get('/media/nitisha/4858-8C4E/Music/Applause.mp3')
>>> print(tag.genre)
None

link for the file: https://drive.google.com/open?id=1zwBSx2fA1EWizxtoXbIDU-yA7hxVDBQ8

**Comment by devsnd** [comment]
Hey, I fixed the problem. TinyTag did not handle a certain field-type of ID3 version 2.2 in MP3s in all their weirdness. I made it work now. You can use the `master` branch until I have made a new release.
