### ISSUE TITLE
duration of voice notes transmitted by WhatsApp as OPUS files 

### ISSUE THREAD

**Issue by marcMeurrens** [devsnd/tinytag#81]
When exiftool's 'Vendor' is 'WhatsApp' and tag.samplerate is 16000
the tag.duration value is exactly 3 times the exact value.

small example opus file + comments are in this file
[tinytag_issue.zip](https://github.com/devsnd/tinytag/files/4046924/tinytag_issue.zip)
or available here :
< https://my.pcloud.com/publink/show?code=kZd8hBkZ1CSxm74Kw2zlW92dOpmYf7M5bO0V >

**Comment by devsnd** [comment]
huh. Apparently Opus is *always* 48kHz, and the sample rate is just there to convert to other files

https://mf4.xiph.org/jenkins/view/opus/job/opusfile-unix/ws/doc/html/structOpusHead.html#a73b80a913eca33d829f1667caee80d9e

So I guess I can hard-code 48kHz in the code and it will always be correct? :thinking:

**Comment by devsnd** [comment]
Hey, this bug has been fixed in the current master branch, I'll release a new version shortly

**Comment by devsnd** [comment]
This is now released in version 1.4.0 and available in pypi.
