### ISSUE TITLE
Getting album image from a flac file

### ISSUE THREAD

**Issue by iboros445** [devsnd/tinytag#82]
when trying to extract album image from a .FLAC file it returns None for me for some reason, MP3 works fine so what can I do with flac?

**Comment by devsnd** [comment]
Can you send me the flac in question?

**Comment by ZekeRedgrave** [comment]
i got the same problem too

here is the sample file

from tinytag import TinyTag
x = "somethin\\in\\here\\blob.flac"

y = TinyTag.get(x, image=True)
y.get_image()

---------- Output -------------------
![image](https://user-images.githubusercontent.com/51784706/97945396-481c7580-1d3c-11eb-8333-10e0104ad90c.png)

**Comment by ironboy1** [comment]
@devsnd I do have the same issue as @ZekeRedgrave and @iboros445, getting the image of mp3 files works fine but for flac files not. Please find attached a sample flac file.
[01 intro.zip](https://github.com/devsnd/tinytag/files/5498160/01.intro.zip)

**Comment by devsnd** [comment]
Hey everybody,

Reading of images in Flac had not been supported by tinytag up to this point. Luckily I found some time to actually implement the feature today. Please just use the git version of tinytag until the next release in which this feature will be available from pip.

Thanks @ironboy1 for providing the sample file!

I hope all of you have a nice day, I wish you all the best in these weird times.
