### ISSUE TITLE
Wrong type for m4a disc and track

### ISSUE THREAD

**Issue by franburstall** [devsnd/tinytag#88]
It seems that tinytag returns ints rather than strings for disc and track when reading m4a files (at least that is the case for the few such files I have).

**Comment by devsnd** [comment]
Can you please provide a sample file for me to be able to debug this issue?

**Comment by franburstall** [comment]
Here is a sample: [sample.m4a.gz](https://github.com/devsnd/tinytag/files/4610183/sample.m4a.gz)

Tinytag gives:

`{"filesize": 5024948, "album": "Blues, Blues Christmas - Volume 1, 1925-1955", "albumartist": "Various Artists", "artist": "The Cats and the Fiddle", "audio_offset": null, "bitrate": 256.0, "channels": 2, "comment": "", "composer": "", "disc": 1, "disc_total": 2, "duration": 154.041179138322, "genre": "Holiday", "samplerate": 44100, "title": "Hep Cat's Birthday", "track": 3, "track_total": 52, "year": "2005"}
`

**Comment by devsnd** [comment]
Oh yeah, I see. Well, that should be fixed easily. You can either make a PR that just casts them to `str` in the `MP4` class (and adjust the test cases accordingly), or wait for me to find the time to make the changes myself on a weekend sometimes :)

**Comment by devsnd** [comment]
Fixed in #97
