### ISSUE TITLE
Bitrate not detected for certain MP3 file

### ISSUE THREAD

**Issue by mathiascode** [devsnd/tinytag#99]
It seems like there is an issue detecting the bitrate for the following MP3 file: [nicotinetestdata.zip](https://github.com/devsnd/tinytag/files/5549957/nicotinetestdata.zip)

I don't know how the file was originally created, but replacing
```
        if self.samplerate:
            self.duration = frames * ID3.samples_per_frame / float(self.samplerate)
```
with
```
        if self.samplerate:
            self.duration = frames * ID3.samples_per_frame / float(self.samplerate)
            self.bitrate = int(round(bitrate_accu / frames))
```

at lines 617-618 in tinytag.py seems to generate the desired bitrate (at least the same value as reported by mediainfo and taglib).

I haven't investigated the issue enough to know if this is a proper fix or not, so any insight from someone more experienced with the codebase would be appreciated.

Edit: this fix is not enough, and seems to break bitrates/lengths for a few other files

**Comment by devsnd** [comment]
Thanks again for the report @mathiascode as well as the proposed fix that led me to the problem origin!

A fix is ready in the master branch. The next version of tinytag will also contain it. You can check out the master branch until then
